import type { CampaignAiInsights, UnknownRecord } from "./types";
import {
  asRecord,
  asString,
  escapeHtml,
  firstPopulatedArray,
  sectionHeading,
} from "./utils";

const numericClaimPattern =
  /\d|\b(?:zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand|million|billion|trillion|percent)\b/i;

export const hasNumericClaim = (value: string) =>
  numericClaimPattern.test(value);

export const getAiSummary = (
  project: UnknownRecord,
  generated?: CampaignAiInsights,
) => {
  if (generated?.summary && !hasNumericClaim(generated.summary)) {
    return generated.summary;
  }

  const aiInsights = asRecord(project.ai_insights);
  const storedSummary = asString(
    project.ai_summary || aiInsights.summary,
  ).trim();
  return hasNumericClaim(storedSummary) ? "" : storedSummary;
};

export const renderAiRecommendations = (
  project: UnknownRecord,
  projectLink: string,
  generated?: CampaignAiInsights,
) => {
  const aiInsights = asRecord(project.ai_insights);
  const recommendations = (
    generated?.recommendations.length
      ? generated.recommendations
      : firstPopulatedArray(
          project.ai_recommendations,
          aiInsights.recommendations,
        )
  )
    .map((value) => {
      if (typeof value === "string") {
        return { title: "Recommendation", body: value.trim() };
      }

      const recommendation = asRecord(value);
      return {
        title: asString(
          recommendation.title || recommendation.heading || "Recommendation",
        ).trim(),
        body: asString(
          recommendation.body ||
            recommendation.description ||
            recommendation.content ||
            recommendation.recommendation,
        ).trim(),
      };
    })
    .filter(({ body }) => body);
  if (recommendations.length === 0) return "";

  const rows = recommendations
    .map(
      ({ title, body }, index) =>
        `<div style="${index < recommendations.length - 1 ? "margin-bottom:25px;" : ""}"><div style="font-size:16px;font-weight:600;">${escapeHtml(title)}</div><p style="font-size:13px;color:#666;line-height:1.5;">${escapeHtml(body)}</p><a href="${projectLink}" style="font-size:14px;color:#ff7400;text-decoration:none;font-weight:600;">View insights</a></div>`,
    )
    .join("");

  return `<div style="margin-top:24px;">${sectionHeading("https://res.cloudinary.com/dyueswnzk/image/upload/v1759780230/id_xmybbv_syv929.png", "AI Recommendations", 30)}<div style="margin-top:14px;background-color:#fffaf5;padding:16px;border-radius:7px;border:1px solid #f0e2d5;border-left:3px solid #ff7400;">${rows}</div><p style="font-size:12px;color:#777;margin-top:10px;line-height:1.4;"><strong>&#9432;</strong> Recommendations are generated by AI from the available campaign data.</p></div>`;
};

// random commit to fix merge deployment
